services:
  app:
    image: ghcr.io/FHNWBAI/python_workshop:latest
    container_name: python_workshop_app
    ports:
      - "8082:8000"        # students will visit http://next:8082
    env_file:
      - .env               # optional, if you want
    restart: unless-stopped
