services:
  app:
    image: ghcr.io/fhnwbai/python_workshop:latest
    container_name: python_workshop_app
    ports:
      - "8082:8000"        # students will visit http://next:8082           # optional, if you want
    restart: unless-stopped
